# Generated by Django 5.2 on 2025-04-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_refundrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundrequest',
            old_name='approval',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='refundrequest',
            name='amount',
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='ticket_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
