# Generated by Django 5.2 on 2025-04-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_approval_refundrequest_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
