# Generated by Django 5.2 on 2025-04-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ticket_price_remove_ticket_seat_and_more'),
        ('app', '0007_alter_refundrequest_approved'),
    ]

    operations = [
    ]
