# Generated by Django 5.2 on 2025-04-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
        ('app', '0008_merge_20250429_1144'),
    ]

    operations = [
    ]
