# Generated by Django 5.2 on 2025-04-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category'),
        ('app', '0009_merge_0004_comment_0008_merge_20250429_1144'),
    ]

    operations = [
    ]
