# Generated by Django 5.2 on 2025-05-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notification_event'),
        ('app', '0010_merge_20250429_1337'),
    ]

    operations = [
    ]
