# Generated by Django 5.2 on 2025-05-21 04:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20250504_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe ser alfanumérico y no debe contener espacios.', regex='^[a-zA-Z0-9]+$')])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='app.ticket')),
            ],
        ),
    ]
