# Generated by Django 5.2 on 2025-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20250504_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveBigIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='new_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado'), ('AGOTADO', 'Agotado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20),
        ),
    ]
