# Generated by Django 5.2 on 2025-05-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ticketdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketdiscount',
            name='ticket',
        ),
    ]
