# Generated by Django 5.2 on 2025-05-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_event_max_capacity_event_new_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], default='ACTIVO', max_length=20),
        ),
    ]
