# Generated by Django 5.2 on 2025-05-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado'), ('AGOTADO', 'Agotado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20),
        ),
    ]
