# Generated by Django 5.2 on 2025-05-24 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_ticketdiscount_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdiscount',
            name='percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
