# Generated by Django 5.2 on 2025-05-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_event_status'),
        ('app', '0014_alter_ticketdiscount_percentage'),
    ]

    operations = [
    ]
