# Generated by Django 5.2 on 2025-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20250528_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado'), ('AGOTADO', 'Agotado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20),
        ),
    ]
